# Part 4 — Data Preprocessing

In this notebook, I will prepare the Ames Housing dataset for machine learning.

## Objectives

- Separate features and target
- Split data into training and validation sets
- Handle missing numerical values
- Handle missing categorical values
- Scale numerical features
- Encode categorical features
- Build a reusable preprocessing pipeline
- Transform the dataset into ML-ready data

### Importing libraries

In [3]:
import pandas as pd
import numpy as np

from pathlib import Path

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler,OneHotEncoder

In [4]:
PROJECT_ROOT=Path.cwd().parent
PROJECT_ROOT

WindowsPath('c:/Users/LENOVO/OneDrive/Desktop/Machine_Learning_Projects/house-price-prediction')

In [5]:
DATA_PATH= PROJECT_ROOT / "data" / "train.csv"

DATA_PATH

WindowsPath('c:/Users/LENOVO/OneDrive/Desktop/Machine_Learning_Projects/house-price-prediction/data/train.csv')

In [8]:
df=pd.read_csv(DATA_PATH)

df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [10]:
TARGET="SalePrice"

X= df.drop(columns=[TARGET])
y=df[TARGET]

print("X shape: ",X.shape)
print("y shape: ",y.shape)

X shape:  (1460, 80)
y shape:  (1460,)

In [16]:
numerical_features=X.select_dtypes(include=["int64","float64"]).columns.tolist()

categorical_features=X.select_dtypes(include=["str"]).columns.tolist()

print("Number of numerical features:", len(numerical_features))
print("Number of categorical features:", len(categorical_features))

Number of numerical features: 37
Number of categorical features: 43

In [17]:
print("Numerical features:")
print(numerical_features)

print("\nCategorical features:")
print(categorical_features)

Numerical features:
['Id', 'MSSubClass', 'LotFrontage', 'LotArea', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd', 'MasVnrArea', 'BsmtFinSF1', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'TotRmsAbvGrd', 'Fireplaces', 'GarageYrBlt', 'GarageCars', 'GarageArea', 'WoodDeckSF', 'OpenPorchSF', 'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'MiscVal', 'MoSold', 'YrSold']

Categorical features:
['MSZoning', 'Street', 'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig', 'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle', 'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2', 'Heating', 'HeatingQC', 'CentralAir', 'Electrical', 'KitchenQual', 'Functional', 'FireplaceQu', 'GarageType', 'GarageFinish', 'GarageQual', 'GarageCond', 'PavedDrive', 'PoolQC', 'Fence', 'MiscFeature', 'SaleType', 'SaleCondition']

In [18]:
X_train,X_valid,y_train,y_valid=train_test_split(X,y,test_size=0.2,random_state=42)

In [19]:
print("X_train:", X_train.shape)
print("X_valid:", X_valid.shape)

print("y_train:", y_train.shape)
print("y_valid:", y_valid.shape)

X_train: (1168, 80)
X_valid: (292, 80)
y_train: (1168,)
y_valid: (292,)

In [21]:
numerical_pipeline=Pipeline(
    steps=[
        ("imputer",SimpleImputer(strategy="median")),
        ("scaler",StandardScaler())
    ]
)

In [28]:
categorical_pipeline=Pipeline(
    steps=[
        ("imputer",SimpleImputer(strategy='most_frequent')),
        ("encoder",OneHotEncoder(handle_unknown='ignore'))
    ]
)

In [29]:
preprocessor=ColumnTransformer(
    transformers=[
        ("num",numerical_pipeline,numerical_features),
        ("cat",categorical_pipeline,categorical_features)    
    ]
)

                         X
                         │
             ┌───────────┴───────────┐
             ↓                       ↓
       Numerical                 Categorical
        Features                  Features
             ↓                       ↓
       Num Pipeline              Cat Pipeline
             ↓                       ↓
    Impute + Scale            Impute + Encode
             └───────────┬───────────┘
                         ↓
                 Processed Features

In [30]:
preprocessor.fit(X_train)

ColumnTransformer(transformers=[('num',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='median')),
                                                 ('scaler', StandardScaler())]),
                                 ['Id', 'MSSubClass', 'LotFrontage', 'LotArea',
                                  'OverallQual', 'OverallCond', 'YearBuilt',
                                  'YearRemodAdd', 'MasVnrArea', 'BsmtFinSF1',
                                  'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF',
                                  '1stFlrSF', '2ndFlrSF', 'LowQualFinSF',
                                  'GrLivArea', 'BsmtFul...
                                 ['MSZoning', 'Street', 'Alley', 'LotShape',
                                  'LandContour', 'Utilities', 'LotConfig',
                                  'LandSlope', 'Neighborhood', 'Condition1',
                                  'Condition2', 'BldgType', 'HouseStyle',
                                  'RoofStyle', 'RoofMatl', 'Exterior1st',
                                  'Exterior2nd', 'MasVnrType', 'ExterQual',
                                  'ExterCond', 'Foundation', 'BsmtQual',
                                  'BsmtCond', 'BsmtExposure', 'BsmtFinType1',
                                  'BsmtFinType2', 'Heating', 'HeatingQC',
                                  'CentralAir', 'Electrical', ...])])

In [31]:
X_train_processed=preprocessor.transform(X_train)

print("Original training shape:", X_train.shape)
print("Processed training shape:", X_train_processed.shape)

Original training shape: (1168, 80)
Processed training shape: (1168, 286)

In [32]:
X_valid_processed=preprocessor.transform(X_valid)

print("Validation original shape:", X_valid.shape)
print("Validation processed shape:", X_valid_processed.shape)

Validation original shape: (292, 80)
Validation processed shape: (292, 286)

In [33]:
if hasattr(X_train_processed,"toarray"):
    X_train_check=X_train_processed.toarray()
else:
    x_train_check=X_train_processed

print(
    "Missing Values:",
    np.isnan(X_train_check).sum()
)

Missing Values: 0

In [37]:
feature_names=preprocessor.get_feature_names_out()

print("Number of processed features:", len(feature_names))

feature_names[:30]

Number of processed features: 286

array(['num__Id', 'num__MSSubClass', 'num__LotFrontage', 'num__LotArea',
       'num__OverallQual', 'num__OverallCond', 'num__YearBuilt',
       'num__YearRemodAdd', 'num__MasVnrArea', 'num__BsmtFinSF1',
       'num__BsmtFinSF2', 'num__BsmtUnfSF', 'num__TotalBsmtSF',
       'num__1stFlrSF', 'num__2ndFlrSF', 'num__LowQualFinSF',
       'num__GrLivArea', 'num__BsmtFullBath', 'num__BsmtHalfBath',
       'num__FullBath', 'num__HalfBath', 'num__BedroomAbvGr',
       'num__KitchenAbvGr', 'num__TotRmsAbvGrd', 'num__Fireplaces',
       'num__GarageYrBlt', 'num__GarageCars', 'num__GarageArea',
       'num__WoodDeckSF', 'num__OpenPorchSF'], dtype=object)

In [42]:
if hasattr(X_train_processed,"toarray"):
    X_train_processed_array=X_train_processed.toarray()
else:
    X_train_processed_array=X_train_processed

X_train_processed_df=pd.DataFrame(
    X_train_processed_array,
    columns=feature_names,
    index=X_train.index
)    

X_train_processed_df.head()

,num__Id,num__MSSubClass,num__LotFrontage,num__LotArea,num__OverallQual,num__OverallCond,num__YearBuilt,num__YearRemodAdd,num__MasVnrArea,num__BsmtFinSF1,...,cat__SaleType_ConLw,cat__SaleType_New,cat__SaleType_Oth,cat__SaleType_WD,cat__SaleCondition_Abnorml,cat__SaleCondition_AdjLand,cat__SaleCondition_Alloca,cat__SaleCondition_Family,cat__SaleCondition_Normal,cat__SaleCondition_Partial
254,-1.119284,-0.866764,-0.012468,-0.212896,-0.820445,0.372217,-0.455469,-1.346063,-0.597889,1.037269,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
1066,0.790464,0.074110,-0.502357,-0.265245,-0.088934,1.268609,0.718609,0.439214,-0.597889,-0.971996,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
638,-0.216152,-0.631546,-0.146074,-0.177841,-0.820445,1.268609,-1.988293,-1.683818,-0.597889,-0.971996,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
799,0.162505,-0.161109,-0.457822,-0.324474,-0.820445,1.268609,-1.107734,-1.683818,0.861522,0.267995,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
380,-0.822944,-0.161109,-0.903175,-0.529035,-0.820445,0.372217,-1.531707,-1.683818,-0.597889,-0.496920,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0

In [43]:
X_train_processed_df.shape

(1168, 286)

In [44]:
X_train_processed_df.isnull().sum().sum()

np.int64(0)

In [ ]:
numeric_processed_columns=[col for col in X_train_processed_df.columns if col.startswith("num__")]

In [55]:
X_train_processed_df[numeric_processed_columns].describe().T[["mean","std"]].head(10)

                           mean       std
num__Id           -4.258390e-17  1.000428
num__MSSubClass    6.995926e-17  1.000428
num__LotFrontage  -2.007527e-16  1.000428
num__LotArea       2.281280e-17  1.000428
num__OverallQual  -5.170902e-17  1.000428
num__OverallCond  -2.281280e-16  1.000428
num__YearBuilt    -1.417435e-15  1.000428
num__YearRemodAdd  4.653812e-15  1.000428
num__MasVnrArea   -4.562560e-18  1.000428
num__BsmtFinSF1    6.463627e-18  1.000428